### ISSUE TITLE
The login Keyring did not get unlocked when you logged into your computer

### ISSUE THREAD

**Issue by logicito** [EmixamPP/linux-enable-ir-emitter#10]
Hi, I used your script to enable the IR emitters with my laptop and Ubuntu 20.04, Howdy alone will not be able to, it works fine until I will reboot or shutdown the laptop, then at the next login after restarting, the white led from the camera will turn on and the IR emitters will stay off and of course face authentication will fail, any idea what could be the problem? Thanks

**Comment by logicito** [comment]
I fixed the startup issue by running the last part of your script, well done. 

Nonetheless now, after logging in for the first time or after a logout/login I get the message: 

"The login Keyring did not get unlocked when you logged into your computer"

Do you know how it can be fixed? Thank you

**Comment by EmixamPP** [comment]
Unfortunately, it's because of Howdy. In fact, it's because of PAM which does not allow the wallet to be unlocked at start-up with an alternative authentication method. 

So, when you first start up, you have to enter the password yourself in the dialog that asks you to unlock the wallet. 

Another problem is that with GNOME the dialog does not always appear (no problem with KDE). The only solution I found is to install seahorse to remove the wallet password. Beware your passwords will then be stored in clear text.

**Comment by logicito** [comment]
Thank you very much, Seashore fixed the problem.
